
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flnzdrgdfeupibaejjar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbnpkcmdkZmV1cGliYWVqamFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMjQyODgsImV4cCI6MjA1NDkwMDI4OH0.ORsyUxDztzV3vkolGVvu0xpeEQsClgmHB7ES8CgWkm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
